# Use root/example as user/password credentials
version: "3.1"

services:
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    restart: always
    ports:
      - "8081:8081"
    environment:
      - VUE_APP_API_BASE_URL=localhost:5000
      - VUE_APP_WEBSOCKETS_BASE_URL=localhost:5050
