# Use root/example as user/password credentials
version: "3.1"

services:
  heart-sms-web:
    container_name: heart-sms-web
    image: heartsms/heart-sms-web
    restart: always
    ports:
      - "127.0.0.1:8081:80"
    volumes:
      # Mount the config directory, then edit/replace web-config.json once the container has started
      - ./heart-web-config:/usr/share/nginx/html/config
